// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s.proto

package org.acq.lz.proto;


import com.google.protobuf.ExtensionRegistry;


public final class SearchServiceFactory {
  private SearchServiceFactory() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchServiceOrBuilder extends
          // @@protoc_insertion_point(interface_extends:SearchService)
          com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code SearchService}
   */
  public static final class SearchService extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:SearchService)
          SearchServiceOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use SearchService.newBuilder() to construct.
    private SearchService(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchService() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new SearchService();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      org.acq.lz.proto.SearchServiceFactory.SearchService.class, org.acq.lz.proto.SearchServiceFactory.SearchService.Builder.class);
    }

    /**
     * Protobuf enum {@code SearchService.SearchScope}
     */
    public enum SearchScope
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>A = 0;</code>
       */
      A(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>A = 0;</code>
       */
      public static final int A_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SearchScope valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static SearchScope forNumber(int value) {
        switch (value) {
          case 0: return A;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SearchScope>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              SearchScope> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<SearchScope>() {
                public SearchScope findValueByNumber(int number) {
                  return SearchScope.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
                  "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return org.acq.lz.proto.SearchServiceFactory.SearchService.getDescriptor().getEnumTypes().get(0);
      }

      private static final SearchScope[] VALUES = values();

      public static SearchScope valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SearchScope(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SearchService.SearchScope)
    }

    /**
     * Protobuf enum {@code SearchService.SearchFilter}
     */
    public enum SearchFilter
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>B = 0;</code>
       */
      B(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>B = 0;</code>
       */
      public static final int B_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SearchFilter valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static SearchFilter forNumber(int value) {
        switch (value) {
          case 0: return B;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SearchFilter>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              SearchFilter> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<SearchFilter>() {
                public SearchFilter findValueByNumber(int number) {
                  return SearchFilter.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
                  "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return org.acq.lz.proto.SearchServiceFactory.SearchService.getDescriptor().getEnumTypes().get(1);
      }

      private static final SearchFilter[] VALUES = values();

      public static SearchFilter valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SearchFilter(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SearchService.SearchFilter)
    }

    public interface CommonRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SearchService.CommonRequest)
            com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string searchType = 1;</code>
       * @return The searchType.
       */
      java.lang.String getSearchType();
      /**
       * <code>string searchType = 1;</code>
       * @return The bytes for searchType.
       */
      com.google.protobuf.ByteString
      getSearchTypeBytes();

      /**
       * <code>string searchWord = 2;</code>
       * @return The searchWord.
       */
      java.lang.String getSearchWord();
      /**
       * <code>string searchWord = 2;</code>
       * @return The bytes for searchWord.
       */
      com.google.protobuf.ByteString
      getSearchWordBytes();

      /**
       * <code>int32 currentPage = 3;</code>
       * @return The currentPage.
       */
      int getCurrentPage();

      /**
       * <code>int32 pageSize = 4;</code>
       * @return The pageSize.
       */
      int getPageSize();

      /**
       * <code>.SearchService.SearchScope searchScope = 5;</code>
       * @return The enum numeric value on the wire for searchScope.
       */
      int getSearchScopeValue();
      /**
       * <code>.SearchService.SearchScope searchScope = 5;</code>
       * @return The searchScope.
       */
      org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope getSearchScope();

      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @return A list containing the searchFilter.
       */
      java.util.List<org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter> getSearchFilterList();
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @return The count of searchFilter.
       */
      int getSearchFilterCount();
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @param index The index of the element to return.
       * @return The searchFilter at the given index.
       */
      org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter getSearchFilter(int index);
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @return A list containing the enum numeric values on the wire for searchFilter.
       */
      java.util.List<java.lang.Integer>
      getSearchFilterValueList();
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of searchFilter at the given index.
       */
      int getSearchFilterValue(int index);
    }
    /**
     * Protobuf type {@code SearchService.CommonRequest}
     */
    public static final class CommonRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:SearchService.CommonRequest)
            CommonRequestOrBuilder {
      private static final long serialVersionUID = 0L;
      // Use CommonRequest.newBuilder() to construct.
      private CommonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CommonRequest() {
        searchType_ = "";
        searchWord_ = "";
        searchScope_ = 0;
        searchFilter_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
              UnusedPrivateParameter unused) {
        return new CommonRequest();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_CommonRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_CommonRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.class, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.Builder.class);
      }

      public static final int SEARCHTYPE_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object searchType_ = "";
      /**
       * <code>string searchType = 1;</code>
       * @return The searchType.
       */
      @java.lang.Override
      public java.lang.String getSearchType() {
        java.lang.Object ref = searchType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          searchType_ = s;
          return s;
        }
      }
      /**
       * <code>string searchType = 1;</code>
       * @return The bytes for searchType.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getSearchTypeBytes() {
        java.lang.Object ref = searchType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          searchType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SEARCHWORD_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object searchWord_ = "";
      /**
       * <code>string searchWord = 2;</code>
       * @return The searchWord.
       */
      @java.lang.Override
      public java.lang.String getSearchWord() {
        java.lang.Object ref = searchWord_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          searchWord_ = s;
          return s;
        }
      }
      /**
       * <code>string searchWord = 2;</code>
       * @return The bytes for searchWord.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getSearchWordBytes() {
        java.lang.Object ref = searchWord_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          searchWord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CURRENTPAGE_FIELD_NUMBER = 3;
      private int currentPage_ = 0;
      /**
       * <code>int32 currentPage = 3;</code>
       * @return The currentPage.
       */
      @java.lang.Override
      public int getCurrentPage() {
        return currentPage_;
      }

      public static final int PAGESIZE_FIELD_NUMBER = 4;
      private int pageSize_ = 0;
      /**
       * <code>int32 pageSize = 4;</code>
       * @return The pageSize.
       */
      @java.lang.Override
      public int getPageSize() {
        return pageSize_;
      }

      public static final int SEARCHSCOPE_FIELD_NUMBER = 5;
      private int searchScope_ = 0;
      /**
       * <code>.SearchService.SearchScope searchScope = 5;</code>
       * @return The enum numeric value on the wire for searchScope.
       */
      @java.lang.Override public int getSearchScopeValue() {
        return searchScope_;
      }
      /**
       * <code>.SearchService.SearchScope searchScope = 5;</code>
       * @return The searchScope.
       */
      @java.lang.Override public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope getSearchScope() {
        org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope result = org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope.forNumber(searchScope_);
        return result == null ? org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope.UNRECOGNIZED : result;
      }

      public static final int SEARCHFILTER_FIELD_NUMBER = 6;
      @SuppressWarnings("serial")
      private java.util.List<java.lang.Integer> searchFilter_;
      private static final com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter> searchFilter_converter_ =
              new com.google.protobuf.Internal.ListAdapter.Converter<
                      java.lang.Integer, org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter>() {
                public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter convert(java.lang.Integer from) {
                  org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter result = org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter.forNumber(from);
                  return result == null ? org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter.UNRECOGNIZED : result;
                }
              };
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @return A list containing the searchFilter.
       */
      @java.lang.Override
      public java.util.List<org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter> getSearchFilterList() {
        return new com.google.protobuf.Internal.ListAdapter<
                java.lang.Integer, org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter>(searchFilter_, searchFilter_converter_);
      }
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @return The count of searchFilter.
       */
      @java.lang.Override
      public int getSearchFilterCount() {
        return searchFilter_.size();
      }
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @param index The index of the element to return.
       * @return The searchFilter at the given index.
       */
      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter getSearchFilter(int index) {
        return searchFilter_converter_.convert(searchFilter_.get(index));
      }
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @return A list containing the enum numeric values on the wire for searchFilter.
       */
      @java.lang.Override
      public java.util.List<java.lang.Integer>
      getSearchFilterValueList() {
        return searchFilter_;
      }
      /**
       * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of searchFilter at the given index.
       */
      @java.lang.Override
      public int getSearchFilterValue(int index) {
        return searchFilter_.get(index);
      }
      private int searchFilterMemoizedSerializedSize;

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
        getSerializedSize();
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(searchType_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, searchType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(searchWord_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, searchWord_);
        }
        if (currentPage_ != 0) {
          output.writeInt32(3, currentPage_);
        }
        if (pageSize_ != 0) {
          output.writeInt32(4, pageSize_);
        }
        if (searchScope_ != org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope.A.getNumber()) {
          output.writeEnum(5, searchScope_);
        }
        if (getSearchFilterList().size() > 0) {
          output.writeUInt32NoTag(50);
          output.writeUInt32NoTag(searchFilterMemoizedSerializedSize);
        }
        for (int i = 0; i < searchFilter_.size(); i++) {
          output.writeEnumNoTag(searchFilter_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(searchType_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, searchType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(searchWord_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, searchWord_);
        }
        if (currentPage_ != 0) {
          size += com.google.protobuf.CodedOutputStream
                  .computeInt32Size(3, currentPage_);
        }
        if (pageSize_ != 0) {
          size += com.google.protobuf.CodedOutputStream
                  .computeInt32Size(4, pageSize_);
        }
        if (searchScope_ != org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope.A.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
                  .computeEnumSize(5, searchScope_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < searchFilter_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
                    .computeEnumSizeNoTag(searchFilter_.get(i));
          }
          size += dataSize;
          if (!getSearchFilterList().isEmpty()) {  size += 1;
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt32SizeNoTag(dataSize);
          }searchFilterMemoizedSerializedSize = dataSize;
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
          return true;
        }
        if (!(obj instanceof org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest)) {
          return super.equals(obj);
        }
        org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest other = (org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest) obj;

        if (!getSearchType()
                .equals(other.getSearchType())) return false;
        if (!getSearchWord()
                .equals(other.getSearchWord())) return false;
        if (getCurrentPage()
                != other.getCurrentPage()) return false;
        if (getPageSize()
                != other.getPageSize()) return false;
        if (searchScope_ != other.searchScope_) return false;
        if (!searchFilter_.equals(other.searchFilter_)) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SEARCHTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSearchType().hashCode();
        hash = (37 * hash) + SEARCHWORD_FIELD_NUMBER;
        hash = (53 * hash) + getSearchWord().hashCode();
        hash = (37 * hash) + CURRENTPAGE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentPage();
        hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
        hash = (53 * hash) + getPageSize();
        hash = (37 * hash) + SEARCHSCOPE_FIELD_NUMBER;
        hash = (53 * hash) + searchScope_;
        if (getSearchFilterCount() > 0) {
          hash = (37 * hash) + SEARCHFILTER_FIELD_NUMBER;
          hash = (53 * hash) + searchFilter_.hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              java.nio.ByteBuffer data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              java.nio.ByteBuffer data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SearchService.CommonRequest}
       */
      public static final class Builder extends
              com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
              // @@protoc_insertion_point(builder_implements:SearchService.CommonRequest)
              org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
          return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_CommonRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
          return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_CommonRequest_fieldAccessorTable
                  .ensureFieldAccessorsInitialized(
                          org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.class, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.Builder.class);
        }

        // Construct using org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          searchType_ = "";
          searchWord_ = "";
          currentPage_ = 0;
          pageSize_ = 0;
          searchScope_ = 0;
          searchFilter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
          return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_CommonRequest_descriptor;
        }

        @java.lang.Override
        public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest getDefaultInstanceForType() {
          return org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.getDefaultInstance();
        }

        @java.lang.Override
        public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest build() {
          org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest buildPartial() {
          org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest result = new org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest(this);
          buildPartialRepeatedFields(result);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartialRepeatedFields(org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest result) {
          if (((bitField0_ & 0x00000020) != 0)) {
            searchFilter_ = java.util.Collections.unmodifiableList(searchFilter_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.searchFilter_ = searchFilter_;
        }

        private void buildPartial0(org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.searchType_ = searchType_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.searchWord_ = searchWord_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.currentPage_ = currentPage_;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.pageSize_ = pageSize_;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.searchScope_ = searchScope_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest) {
            return mergeFrom((org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest other) {
          if (other == org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.getDefaultInstance()) return this;
          if (!other.getSearchType().isEmpty()) {
            searchType_ = other.searchType_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.getSearchWord().isEmpty()) {
            searchWord_ = other.searchWord_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (other.getCurrentPage() != 0) {
            setCurrentPage(other.getCurrentPage());
          }
          if (other.getPageSize() != 0) {
            setPageSize(other.getPageSize());
          }
          if (other.searchScope_ != 0) {
            setSearchScopeValue(other.getSearchScopeValue());
          }
          if (!other.searchFilter_.isEmpty()) {
            if (searchFilter_.isEmpty()) {
              searchFilter_ = other.searchFilter_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureSearchFilterIsMutable();
              searchFilter_.addAll(other.searchFilter_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  searchType_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  searchWord_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 24: {
                  currentPage_ = input.readInt32();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                case 32: {
                  pageSize_ = input.readInt32();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 32
                case 40: {
                  searchScope_ = input.readEnum();
                  bitField0_ |= 0x00000010;
                  break;
                } // case 40
                case 48: {
                  int tmpRaw = input.readEnum();
                  ensureSearchFilterIsMutable();
                  searchFilter_.add(tmpRaw);
                  break;
                } // case 48
                case 50: {
                  int length = input.readRawVarint32();
                  int oldLimit = input.pushLimit(length);
                  while(input.getBytesUntilLimit() > 0) {
                    int tmpRaw = input.readEnum();
                    ensureSearchFilterIsMutable();
                    searchFilter_.add(tmpRaw);
                  }
                  input.popLimit(oldLimit);
                  break;
                } // case 50
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object searchType_ = "";
        /**
         * <code>string searchType = 1;</code>
         * @return The searchType.
         */
        public java.lang.String getSearchType() {
          java.lang.Object ref = searchType_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            searchType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string searchType = 1;</code>
         * @return The bytes for searchType.
         */
        public com.google.protobuf.ByteString
        getSearchTypeBytes() {
          java.lang.Object ref = searchType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            searchType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string searchType = 1;</code>
         * @param value The searchType to set.
         * @return This builder for chaining.
         */
        public Builder setSearchType(
                java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          searchType_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string searchType = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearSearchType() {
          searchType_ = getDefaultInstance().getSearchType();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string searchType = 1;</code>
         * @param value The bytes for searchType to set.
         * @return This builder for chaining.
         */
        public Builder setSearchTypeBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          searchType_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private java.lang.Object searchWord_ = "";
        /**
         * <code>string searchWord = 2;</code>
         * @return The searchWord.
         */
        public java.lang.String getSearchWord() {
          java.lang.Object ref = searchWord_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            searchWord_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string searchWord = 2;</code>
         * @return The bytes for searchWord.
         */
        public com.google.protobuf.ByteString
        getSearchWordBytes() {
          java.lang.Object ref = searchWord_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            searchWord_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string searchWord = 2;</code>
         * @param value The searchWord to set.
         * @return This builder for chaining.
         */
        public Builder setSearchWord(
                java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          searchWord_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string searchWord = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearSearchWord() {
          searchWord_ = getDefaultInstance().getSearchWord();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string searchWord = 2;</code>
         * @param value The bytes for searchWord to set.
         * @return This builder for chaining.
         */
        public Builder setSearchWordBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          searchWord_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private int currentPage_ ;
        /**
         * <code>int32 currentPage = 3;</code>
         * @return The currentPage.
         */
        @java.lang.Override
        public int getCurrentPage() {
          return currentPage_;
        }
        /**
         * <code>int32 currentPage = 3;</code>
         * @param value The currentPage to set.
         * @return This builder for chaining.
         */
        public Builder setCurrentPage(int value) {

          currentPage_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>int32 currentPage = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCurrentPage() {
          bitField0_ = (bitField0_ & ~0x00000004);
          currentPage_ = 0;
          onChanged();
          return this;
        }

        private int pageSize_ ;
        /**
         * <code>int32 pageSize = 4;</code>
         * @return The pageSize.
         */
        @java.lang.Override
        public int getPageSize() {
          return pageSize_;
        }
        /**
         * <code>int32 pageSize = 4;</code>
         * @param value The pageSize to set.
         * @return This builder for chaining.
         */
        public Builder setPageSize(int value) {

          pageSize_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>int32 pageSize = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearPageSize() {
          bitField0_ = (bitField0_ & ~0x00000008);
          pageSize_ = 0;
          onChanged();
          return this;
        }

        private int searchScope_ = 0;
        /**
         * <code>.SearchService.SearchScope searchScope = 5;</code>
         * @return The enum numeric value on the wire for searchScope.
         */
        @java.lang.Override public int getSearchScopeValue() {
          return searchScope_;
        }
        /**
         * <code>.SearchService.SearchScope searchScope = 5;</code>
         * @param value The enum numeric value on the wire for searchScope to set.
         * @return This builder for chaining.
         */
        public Builder setSearchScopeValue(int value) {
          searchScope_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }
        /**
         * <code>.SearchService.SearchScope searchScope = 5;</code>
         * @return The searchScope.
         */
        @java.lang.Override
        public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope getSearchScope() {
          org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope result = org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope.forNumber(searchScope_);
          return result == null ? org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope.UNRECOGNIZED : result;
        }
        /**
         * <code>.SearchService.SearchScope searchScope = 5;</code>
         * @param value The searchScope to set.
         * @return This builder for chaining.
         */
        public Builder setSearchScope(org.acq.lz.proto.SearchServiceFactory.SearchService.SearchScope value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          searchScope_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.SearchService.SearchScope searchScope = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearSearchScope() {
          bitField0_ = (bitField0_ & ~0x00000010);
          searchScope_ = 0;
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Integer> searchFilter_ =
                java.util.Collections.emptyList();
        private void ensureSearchFilterIsMutable() {
          if (!((bitField0_ & 0x00000020) != 0)) {
            searchFilter_ = new java.util.ArrayList<java.lang.Integer>(searchFilter_);
            bitField0_ |= 0x00000020;
          }
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @return A list containing the searchFilter.
         */
        public java.util.List<org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter> getSearchFilterList() {
          return new com.google.protobuf.Internal.ListAdapter<
                  java.lang.Integer, org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter>(searchFilter_, searchFilter_converter_);
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @return The count of searchFilter.
         */
        public int getSearchFilterCount() {
          return searchFilter_.size();
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param index The index of the element to return.
         * @return The searchFilter at the given index.
         */
        public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter getSearchFilter(int index) {
          return searchFilter_converter_.convert(searchFilter_.get(index));
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param index The index to set the value at.
         * @param value The searchFilter to set.
         * @return This builder for chaining.
         */
        public Builder setSearchFilter(
                int index, org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSearchFilterIsMutable();
          searchFilter_.set(index, value.getNumber());
          onChanged();
          return this;
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param value The searchFilter to add.
         * @return This builder for chaining.
         */
        public Builder addSearchFilter(org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSearchFilterIsMutable();
          searchFilter_.add(value.getNumber());
          onChanged();
          return this;
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param values The searchFilter to add.
         * @return This builder for chaining.
         */
        public Builder addAllSearchFilter(
                java.lang.Iterable<? extends org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter> values) {
          ensureSearchFilterIsMutable();
          for (org.acq.lz.proto.SearchServiceFactory.SearchService.SearchFilter value : values) {
            searchFilter_.add(value.getNumber());
          }
          onChanged();
          return this;
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearSearchFilter() {
          searchFilter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @return A list containing the enum numeric values on the wire for searchFilter.
         */
        public java.util.List<java.lang.Integer>
        getSearchFilterValueList() {
          return java.util.Collections.unmodifiableList(searchFilter_);
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param index The index of the value to return.
         * @return The enum numeric value on the wire of searchFilter at the given index.
         */
        public int getSearchFilterValue(int index) {
          return searchFilter_.get(index);
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param index The index to set the value at.
         * @param value The enum numeric value on the wire for searchFilter to set.
         * @return This builder for chaining.
         */
        public Builder setSearchFilterValue(
                int index, int value) {
          ensureSearchFilterIsMutable();
          searchFilter_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param value The enum numeric value on the wire for searchFilter to add.
         * @return This builder for chaining.
         */
        public Builder addSearchFilterValue(int value) {
          ensureSearchFilterIsMutable();
          searchFilter_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .SearchService.SearchFilter searchFilter = 6;</code>
         * @param values The enum numeric values on the wire for searchFilter to add.
         * @return This builder for chaining.
         */
        public Builder addAllSearchFilterValue(
                java.lang.Iterable<java.lang.Integer> values) {
          ensureSearchFilterIsMutable();
          for (int value : values) {
            searchFilter_.add(value);
          }
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:SearchService.CommonRequest)
      }

      // @@protoc_insertion_point(class_scope:SearchService.CommonRequest)
      private static final org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest();
      }

      public static org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CommonRequest>
              PARSER = new com.google.protobuf.AbstractParser<CommonRequest>() {
        @java.lang.Override
        public CommonRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                    .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<CommonRequest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CommonRequest> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface SearchRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SearchService.SearchRequest)
            com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.SearchService.CommonRequest commonrequest = 1;</code>
       * @return Whether the commonrequest field is set.
       */
      boolean hasCommonrequest();
      /**
       * <code>.SearchService.CommonRequest commonrequest = 1;</code>
       * @return The commonrequest.
       */
      org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest getCommonrequest();
      /**
       * <code>.SearchService.CommonRequest commonrequest = 1;</code>
       */
      org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequestOrBuilder getCommonrequestOrBuilder();
    }
    /**
     * Protobuf type {@code SearchService.SearchRequest}
     */
    public static final class SearchRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:SearchService.SearchRequest)
            SearchRequestOrBuilder {
      private static final long serialVersionUID = 0L;
      // Use SearchRequest.newBuilder() to construct.
      private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private SearchRequest() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
              UnusedPrivateParameter unused) {
        return new SearchRequest();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_SearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_SearchRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest.class, org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest.Builder.class);
      }

      public static final int COMMONREQUEST_FIELD_NUMBER = 1;
      private org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest commonrequest_;
      /**
       * <code>.SearchService.CommonRequest commonrequest = 1;</code>
       * @return Whether the commonrequest field is set.
       */
      @java.lang.Override
      public boolean hasCommonrequest() {
        return commonrequest_ != null;
      }
      /**
       * <code>.SearchService.CommonRequest commonrequest = 1;</code>
       * @return The commonrequest.
       */
      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest getCommonrequest() {
        return commonrequest_ == null ? org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.getDefaultInstance() : commonrequest_;
      }
      /**
       * <code>.SearchService.CommonRequest commonrequest = 1;</code>
       */
      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequestOrBuilder getCommonrequestOrBuilder() {
        return commonrequest_ == null ? org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.getDefaultInstance() : commonrequest_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
        if (commonrequest_ != null) {
          output.writeMessage(1, getCommonrequest());
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (commonrequest_ != null) {
          size += com.google.protobuf.CodedOutputStream
                  .computeMessageSize(1, getCommonrequest());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
          return true;
        }
        if (!(obj instanceof org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest)) {
          return super.equals(obj);
        }
        org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest other = (org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest) obj;

        if (hasCommonrequest() != other.hasCommonrequest()) return false;
        if (hasCommonrequest()) {
          if (!getCommonrequest()
                  .equals(other.getCommonrequest())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCommonrequest()) {
          hash = (37 * hash) + COMMONREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getCommonrequest().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              java.nio.ByteBuffer data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              java.nio.ByteBuffer data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SearchService.SearchRequest}
       */
      public static final class Builder extends
              com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
              // @@protoc_insertion_point(builder_implements:SearchService.SearchRequest)
              org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
          return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_SearchRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
          return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_SearchRequest_fieldAccessorTable
                  .ensureFieldAccessorsInitialized(
                          org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest.class, org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest.Builder.class);
        }

        // Construct using org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          commonrequest_ = null;
          if (commonrequestBuilder_ != null) {
            commonrequestBuilder_.dispose();
            commonrequestBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
          return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_SearchRequest_descriptor;
        }

        @java.lang.Override
        public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest getDefaultInstanceForType() {
          return org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest.getDefaultInstance();
        }

        @java.lang.Override
        public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest build() {
          org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest buildPartial() {
          org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest result = new org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.commonrequest_ = commonrequestBuilder_ == null
                    ? commonrequest_
                    : commonrequestBuilder_.build();
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest) {
            return mergeFrom((org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest other) {
          if (other == org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest.getDefaultInstance()) return this;
          if (other.hasCommonrequest()) {
            mergeCommonrequest(other.getCommonrequest());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  input.readMessage(
                          getCommonrequestFieldBuilder().getBuilder(),
                          extensionRegistry);
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest commonrequest_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.Builder, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequestOrBuilder> commonrequestBuilder_;
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         * @return Whether the commonrequest field is set.
         */
        public boolean hasCommonrequest() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         * @return The commonrequest.
         */
        public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest getCommonrequest() {
          if (commonrequestBuilder_ == null) {
            return commonrequest_ == null ? org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.getDefaultInstance() : commonrequest_;
          } else {
            return commonrequestBuilder_.getMessage();
          }
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         */
        public Builder setCommonrequest(org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest value) {
          if (commonrequestBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            commonrequest_ = value;
          } else {
            commonrequestBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         */
        public Builder setCommonrequest(
                org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.Builder builderForValue) {
          if (commonrequestBuilder_ == null) {
            commonrequest_ = builderForValue.build();
          } else {
            commonrequestBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         */
        public Builder mergeCommonrequest(org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest value) {
          if (commonrequestBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0) &&
                    commonrequest_ != null &&
                    commonrequest_ != org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.getDefaultInstance()) {
              getCommonrequestBuilder().mergeFrom(value);
            } else {
              commonrequest_ = value;
            }
          } else {
            commonrequestBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         */
        public Builder clearCommonrequest() {
          bitField0_ = (bitField0_ & ~0x00000001);
          commonrequest_ = null;
          if (commonrequestBuilder_ != null) {
            commonrequestBuilder_.dispose();
            commonrequestBuilder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         */
        public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.Builder getCommonrequestBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getCommonrequestFieldBuilder().getBuilder();
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         */
        public org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequestOrBuilder getCommonrequestOrBuilder() {
          if (commonrequestBuilder_ != null) {
            return commonrequestBuilder_.getMessageOrBuilder();
          } else {
            return commonrequest_ == null ?
                    org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.getDefaultInstance() : commonrequest_;
          }
        }
        /**
         * <code>.SearchService.CommonRequest commonrequest = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.Builder, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequestOrBuilder>
        getCommonrequestFieldBuilder() {
          if (commonrequestBuilder_ == null) {
            commonrequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                    org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequest.Builder, org.acq.lz.proto.SearchServiceFactory.SearchService.CommonRequestOrBuilder>(
                    getCommonrequest(),
                    getParentForChildren(),
                    isClean());
            commonrequest_ = null;
          }
          return commonrequestBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:SearchService.SearchRequest)
      }

      // @@protoc_insertion_point(class_scope:SearchService.SearchRequest)
      private static final org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest();
      }

      public static org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<SearchRequest>
              PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
        @java.lang.Override
        public SearchRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                    .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<SearchRequest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<SearchRequest> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService.SearchRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.acq.lz.proto.SearchServiceFactory.SearchService)) {
        return super.equals(obj);
      }
      org.acq.lz.proto.SearchServiceFactory.SearchService other = (org.acq.lz.proto.SearchServiceFactory.SearchService) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static org.acq.lz.proto.SearchServiceFactory.SearchService parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.acq.lz.proto.SearchServiceFactory.SearchService prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SearchService}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:SearchService)
            org.acq.lz.proto.SearchServiceFactory.SearchServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.acq.lz.proto.SearchServiceFactory.SearchService.class, org.acq.lz.proto.SearchServiceFactory.SearchService.Builder.class);
      }

      // Construct using org.acq.lz.proto.SearchServiceFactory.SearchService.newBuilder()
      private Builder() {

      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.acq.lz.proto.SearchServiceFactory.internal_static_SearchService_descriptor;
      }

      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService getDefaultInstanceForType() {
        return org.acq.lz.proto.SearchServiceFactory.SearchService.getDefaultInstance();
      }

      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService build() {
        org.acq.lz.proto.SearchServiceFactory.SearchService result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.acq.lz.proto.SearchServiceFactory.SearchService buildPartial() {
        org.acq.lz.proto.SearchServiceFactory.SearchService result = new org.acq.lz.proto.SearchServiceFactory.SearchService(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.acq.lz.proto.SearchServiceFactory.SearchService) {
          return mergeFrom((org.acq.lz.proto.SearchServiceFactory.SearchService)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.acq.lz.proto.SearchServiceFactory.SearchService other) {
        if (other == org.acq.lz.proto.SearchServiceFactory.SearchService.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SearchService)
    }

    // @@protoc_insertion_point(class_scope:SearchService)
    private static final org.acq.lz.proto.SearchServiceFactory.SearchService DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.acq.lz.proto.SearchServiceFactory.SearchService();
    }

    public static org.acq.lz.proto.SearchServiceFactory.SearchService getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchService>
            PARSER = new com.google.protobuf.AbstractParser<SearchService>() {
      @java.lang.Override
      public SearchService parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SearchService> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchService> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.acq.lz.proto.SearchServiceFactory.SearchService getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_SearchService_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_SearchService_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_SearchService_CommonRequest_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_SearchService_CommonRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_SearchService_SearchRequest_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_SearchService_SearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\007s.proto\"\307\002\n\rSearchService\032\302\001\n\rCommonRe" +
                    "quest\022\022\n\nsearchType\030\001 \001(\t\022\022\n\nsearchWord\030" +
                    "\002 \001(\t\022\023\n\013currentPage\030\003 \001(\005\022\020\n\010pageSize\030\004" +
                    " \001(\005\022/\n\013searchScope\030\005 \001(\0162\032.SearchServic" +
                    "e.SearchScope\0221\n\014searchFilter\030\006 \003(\0162\033.Se" +
                    "archService.SearchFilter\032D\n\rSearchReques" +
                    "t\0223\n\rcommonrequest\030\001 \001(\0132\034.SearchService" +
                    ".CommonRequest\"\024\n\013SearchScope\022\005\n\001A\020\000\"\025\n\014" +
                    "SearchFilter\022\005\n\001B\020\000B(\n\020org.acq.lz.protoB" +
                    "\024SearchServiceFactoryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_SearchService_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_SearchService_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_SearchService_descriptor,
            new java.lang.String[] { });
    internal_static_SearchService_CommonRequest_descriptor =
            internal_static_SearchService_descriptor.getNestedTypes().get(0);
    internal_static_SearchService_CommonRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_SearchService_CommonRequest_descriptor,
            new java.lang.String[] { "SearchType", "SearchWord", "CurrentPage", "PageSize", "SearchScope", "SearchFilter", });
    internal_static_SearchService_SearchRequest_descriptor =
            internal_static_SearchService_descriptor.getNestedTypes().get(1);
    internal_static_SearchService_SearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_SearchService_SearchRequest_descriptor,
            new java.lang.String[] { "Commonrequest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
